### ISSUE TITLE
Sharing GL context with three.js

### ISSUE THREAD

**Issue by bilgorajskim** [yanchith/webglutenfree#54]
Hi.

I'm trying to incorporate webglutenfree into a big three.js-based app. Both libs need to share the same GL context.
Three.js can reset its internal state, but I see no way to do so in webglutenfree.
In three.js I can do:
```
threeInstance.state.reset();
```
And that will cause three.js to bind programs, uniforms etc. again. 
There needs to be something like that on webglutenfree side as well.

**Comment by yanchith** [comment]
Hey @bilgorajskim , sorry for the late reply. I must have missed the notification, did you manage to solve your problem meanwhile?

I don't think there is something in webglutenfree that suits your needs exactly, but in theory it shouldn't be a huge problem to implement it.

There is a `State` class in [state.ts](https://github.com/yanchith/webglutenfree/blob/master/src/state.ts#L109) which does most but not all state-setting calls to WebGL. It currently thinks it is the only citizen accessing WebGL and therefore it both asserts a lot of things, and tries to optimize gl calls by doing some very simple state diffing. Adding a `reset()` method on `State` and also propagating it outwards to the `Device` should be doable.

**Comment by yanchith** [comment]
So I finally got around to doing this (#58). In theory it should work, but I didn't try any real integration with other WebGL libraries, so there might still be issues that need ironing out.
